---
    deployment:
      tasks:
        - export REPOPATH=/var/www/u1125519/repo/*
        - export SITEPATH=/var/www/u1125519/public_html/bulliador.site
        - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH