---
deployment:
tasks:
- export DEPLOYPATH=/var/www/u1125519/public_html/bulliador.site
- /bin/cp -R css $DEPLOYPATH
- /bin/cp -R img $DEPLOYPATH
- /bin/cp -R project_bouncy $DEPLOYPATH
- /bin/cp index.html $DEPLOYPATH